# Generated by Django 5.1.2 on 2024-10-19 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_stats_light'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='PerfectStats',
        ),
        migrations.CreateModel(
            name='RealStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.FloatField()),
                ('ambientTemperature', models.FloatField()),
                ('ambientHumidity', models.FloatField()),
                ('soilMoistur', models.FloatField()),
                ('soilTemperature', models.FloatField()),
                ('soilPh', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.plot')),
            ],
        ),
    ]
